### ISSUE TITLE
collision check in the inner plugin

### ISSUE THREAD

**Issue by simonschmeisser** [marip8/sampling_kinematics_plugin#5]
https://github.com/marip8/sampling_kinematics_plugin/blob/9e57dcc2ed13144189b14edc537badb0f16c624c/sampling_kinematics_plugin/src/external_axis_sampling_kinematics_plugin.cpp#L317

you could also adjust the robot_seed_state to the new rail position and do the collision check in the inner plugin. That way you would potentially get more solutions in cases where the closest solution is in collision but another one exists further away. This will of course increase the cost if none of the solutions (for a given discretization ) are valid.

Alternatively you could also consider sorting before collision-checking as sorting is much faster. Or combine the two by using the variant of the inner IK plugin that returns all solutions, sort by distance accross all discretizations and only then do the collision checking

**Comment by marip8** [comment]
> you could also adjust the robot_seed_state to the new rail position and do the collision check in the inner plugin.

At least for the OPW kinematics plugin, it only expects the seed state to have 6 values. I can't easily pass it values for the external axes, and I can't easily update it's `RobotState` object with the external axis values either, as far as I know. Either way, I couldn't get the robot plugin to function properly with the callback, maybe because it was trying to collision check with the external axis in the wrong position

> Alternatively you could also consider sorting before collision-checking as sorting is much faster. Or combine the two by using the variant of the inner IK plugin that returns all solutions, sort by distance accross all discretizations and only then do the collision checking

I like this idea and implemented it in #8. I think this should significantly cut down on the number of times the validity callback is entered
